title: Marta Pytel
logo: https://raw.githubusercontent.com/martapytel/images/main/Profile%20photo-min.jpg
description: Business Analyst & Deputy Product Owner
<script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>
<div class="badge-base LI-profile-badge" data-locale="en_US" data-size="medium" data-theme="light" data-type="VERTICAL" data-vanity="mpytel94" data-version="v1"><a class="badge-base__link LI-simple-link" href="https://pl.linkedin.com/in/mpytel94?trk=profile-badge">Marta Pytel</a></div>
show_downloads: true
theme: jekyll-theme-minimal

