title: Marta Pytel
logo: https://raw.githubusercontent.com/martapytel/images/main/Untitled%20design.png
description: Business Analyst & Deputy Product Owner
show_downloads: true
theme: jekyll-theme-minimal
