title: Marta Pytel
logo: https://raw.githubusercontent.com/martapytel/images/main/Profile%20photo-min.jpg
description: Business Analyst & Deputy Product Owner
show_downloads: true
theme: jekyll-theme-minimal
